#############################################################################
# Makefile for building: build/MeetingScheduler
# Generated by qmake (3.1) (Qt 5.15.13)
# Project:  MeetingScheduler.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile MeetingScheduler.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Isrc -Isrc/controllers -Isrc/models -Isrc/repository -Isrc/utils -Isrc/views -Isrc/views/userviews -Isrc/views/teacherviews -Isrc/views/studentviews -Idata -I/usr/include/cppconn -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -Ibuild/moc -Ibuild/ui -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = MeetingScheduler1.0.0
DISTDIR = /mnt/d/2025.1/Lap\ trinh\ mang/Meeting_Scheduler_App/build/obj/MeetingScheduler1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lmysqlcppconn /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Sql.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/obj/

####### Files

SOURCES       = src/client/Client1.cpp \
		src/views/userviews/loginwidget.cpp \
		src/views/userviews/registerwidget.cpp \
		src/views/userviews/mainmenu.cpp \
		src/views/teacherviews/TeacherMenuWidget.cpp \
		src/views/teacherviews/timeslotdialog.cpp \
		src/views/teacherviews/viewtimeslotsdialog.cpp \
		src/views/teacherviews/update_timeslot_dialog.cpp \
		src/views/teacherviews/teacherviewmeetingsdialog.cpp \
		src/views/teacherviews/meetingdetaildialog.cpp \
		src/views/teacherviews/meetinghistorydialog.cpp \
		src/views/teacherviews/viewmeetinghistorydialog.cpp \
		src/views/teacherviews/viewweeklymeetingsdialog.cpp \
		src/views/teacherviews/meetingcalendarwidget.cpp \
		src/views/studentviews/StudentMenu.cpp \
		src/views/studentviews/ViewAllTeacherWidget.cpp \
		src/views/studentviews/teacherlistviewer.cpp \
		src/views/studentviews/timeslotcalendar.cpp \
		src/views/studentviews/meetingbooking.cpp \
		src/views/studentviews/meetingcalendarviewer.cpp \
		src/views/studentviews/MeetingDialog.cpp build/moc/moc_loginwidget.cpp \
		build/moc/moc_registerwidget.cpp \
		build/moc/moc_mainmenu.cpp \
		build/moc/moc_TeacherMenuWidget.cpp \
		build/moc/moc_timeslotdialog.cpp \
		build/moc/moc_viewtimeslotsdialog.cpp \
		build/moc/moc_update_timeslot_dialog.cpp \
		build/moc/moc_teacherviewmeetingsdialog.cpp \
		build/moc/moc_meetingdetaildialog.cpp \
		build/moc/moc_meetinghistorydialog.cpp \
		build/moc/moc_viewmeetinghistorydialog.cpp \
		build/moc/moc_viewweeklymeetingsdialog.cpp \
		build/moc/moc_meetingcalendarwidget.cpp \
		build/moc/moc_StudentMenu.cpp \
		build/moc/moc_ViewAllTeacherWidget.cpp \
		build/moc/moc_teacherlistviewer.cpp \
		build/moc/moc_timeslotcalendar.cpp \
		build/moc/moc_meetingbooking.cpp \
		build/moc/moc_meetingcalendarviewer.cpp \
		build/moc/moc_MeetingDialog.cpp
OBJECTS       = build/obj/Client1.o \
		build/obj/loginwidget.o \
		build/obj/registerwidget.o \
		build/obj/mainmenu.o \
		build/obj/TeacherMenuWidget.o \
		build/obj/timeslotdialog.o \
		build/obj/viewtimeslotsdialog.o \
		build/obj/update_timeslot_dialog.o \
		build/obj/teacherviewmeetingsdialog.o \
		build/obj/meetingdetaildialog.o \
		build/obj/meetinghistorydialog.o \
		build/obj/viewmeetinghistorydialog.o \
		build/obj/viewweeklymeetingsdialog.o \
		build/obj/meetingcalendarwidget.o \
		build/obj/StudentMenu.o \
		build/obj/ViewAllTeacherWidget.o \
		build/obj/teacherlistviewer.o \
		build/obj/timeslotcalendar.o \
		build/obj/meetingbooking.o \
		build/obj/meetingcalendarviewer.o \
		build/obj/MeetingDialog.o \
		build/obj/moc_loginwidget.o \
		build/obj/moc_registerwidget.o \
		build/obj/moc_mainmenu.o \
		build/obj/moc_TeacherMenuWidget.o \
		build/obj/moc_timeslotdialog.o \
		build/obj/moc_viewtimeslotsdialog.o \
		build/obj/moc_update_timeslot_dialog.o \
		build/obj/moc_teacherviewmeetingsdialog.o \
		build/obj/moc_meetingdetaildialog.o \
		build/obj/moc_meetinghistorydialog.o \
		build/obj/moc_viewmeetinghistorydialog.o \
		build/obj/moc_viewweeklymeetingsdialog.o \
		build/obj/moc_meetingcalendarwidget.o \
		build/obj/moc_StudentMenu.o \
		build/obj/moc_ViewAllTeacherWidget.o \
		build/obj/moc_teacherlistviewer.o \
		build/obj/moc_timeslotcalendar.o \
		build/obj/moc_meetingbooking.o \
		build/obj/moc_meetingcalendarviewer.o \
		build/obj/moc_MeetingDialog.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		MeetingScheduler.pro src/views/userviews/loginwidget.h \
		src/views/userviews/registerwidget.h \
		src/views/userviews/mainmenu.h \
		src/views/teacherviews/TeacherMenuWidget.h \
		src/views/teacherviews/timeslotdialog.h \
		src/views/teacherviews/viewtimeslotsdialog.h \
		src/views/teacherviews/update_timeslot_dialog.h \
		src/views/teacherviews/teacherviewmeetingsdialog.h \
		src/views/teacherviews/meetingdetaildialog.h \
		src/views/teacherviews/meetinghistorydialog.h \
		src/views/teacherviews/viewmeetinghistorydialog.h \
		src/views/teacherviews/viewweeklymeetingsdialog.h \
		src/views/teacherviews/meetingcalendarwidget.h \
		src/views/studentviews/StudentMenu.h \
		src/views/studentviews/ViewAllTeacherWidget.h \
		src/views/studentviews/teacherlistviewer.h \
		src/views/studentviews/timeslotcalendar.h \
		src/views/studentviews/meetingbooking.h \
		src/views/studentviews/meetingcalendarviewer.h \
		src/views/studentviews/MeetingDialog.h \
		src/views/UserView.h \
		src/views/TeacherView.h \
		src/views/StudentView.h \
		src/controllers/UserController.h \
		src/controllers/TeacherController.h \
		src/controllers/StudentController.h \
		src/controllers/TeacherResponseController.h \
		src/controllers/StudentResponseController.h \
		src/models/User.h \
		src/models/Meeting.h \
		src/models/Timeslot.h \
		src/models/Response.h \
		src/models/Attendance.h \
		src/repository/UserRepository.h \
		src/repository/MeetingRepository.h \
		src/repository/TimeslotRepository.h \
		src/repository/AttendanceRepository.h \
		src/utils/Utils.h \
		src/utils/MessageUtils.h \
		src/Status.h \
		data/Database.h \
		environment.h src/client/Client1.cpp \
		src/views/userviews/loginwidget.cpp \
		src/views/userviews/registerwidget.cpp \
		src/views/userviews/mainmenu.cpp \
		src/views/teacherviews/TeacherMenuWidget.cpp \
		src/views/teacherviews/timeslotdialog.cpp \
		src/views/teacherviews/viewtimeslotsdialog.cpp \
		src/views/teacherviews/update_timeslot_dialog.cpp \
		src/views/teacherviews/teacherviewmeetingsdialog.cpp \
		src/views/teacherviews/meetingdetaildialog.cpp \
		src/views/teacherviews/meetinghistorydialog.cpp \
		src/views/teacherviews/viewmeetinghistorydialog.cpp \
		src/views/teacherviews/viewweeklymeetingsdialog.cpp \
		src/views/teacherviews/meetingcalendarwidget.cpp \
		src/views/studentviews/StudentMenu.cpp \
		src/views/studentviews/ViewAllTeacherWidget.cpp \
		src/views/studentviews/teacherlistviewer.cpp \
		src/views/studentviews/timeslotcalendar.cpp \
		src/views/studentviews/meetingbooking.cpp \
		src/views/studentviews/meetingcalendarviewer.cpp \
		src/views/studentviews/MeetingDialog.cpp
QMAKE_TARGET  = MeetingScheduler
DESTDIR       = build/
TARGET        = build/MeetingScheduler


first: all
####### Build rules

build/MeetingScheduler: build/ui/ui_loginwidget.h build/ui/ui_registerwidget.h build/ui/ui_mainmenu.h build/ui/ui_TeacherMenuWidget.h build/ui/ui_timeslotdialog.h build/ui/ui_viewtimeslotsdialog.h build/ui/ui_update_timeslot_dialog.h build/ui/ui_teacherviewmeetingsdialog.h build/ui/ui_meetingdetaildialog.h build/ui/ui_meetinghistorydialog.h build/ui/ui_viewmeetinghistorydialog.h build/ui/ui_viewweeklymeetingsdialog.h build/ui/ui_StudentMenu.h build/ui/ui_ViewAllTeacherWidget.h build/ui/ui_teacherlistviewer.h build/ui/ui_timeslotcalendar.h build/ui/ui_meetingbooking.h build/ui/ui_meetingcalendarviewer.h build/ui/ui_MeetingDialog.h $(OBJECTS)  
	@test -d build/ || mkdir -p build/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MeetingScheduler.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		MeetingScheduler.pro
	$(QMAKE) -o Makefile MeetingScheduler.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
MeetingScheduler.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile MeetingScheduler.pro

qmake_all: FORCE


all: Makefile build/MeetingScheduler

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/views/userviews/loginwidget.h src/views/userviews/registerwidget.h src/views/userviews/mainmenu.h src/views/teacherviews/TeacherMenuWidget.h src/views/teacherviews/timeslotdialog.h src/views/teacherviews/viewtimeslotsdialog.h src/views/teacherviews/update_timeslot_dialog.h src/views/teacherviews/teacherviewmeetingsdialog.h src/views/teacherviews/meetingdetaildialog.h src/views/teacherviews/meetinghistorydialog.h src/views/teacherviews/viewmeetinghistorydialog.h src/views/teacherviews/viewweeklymeetingsdialog.h src/views/teacherviews/meetingcalendarwidget.h src/views/studentviews/StudentMenu.h src/views/studentviews/ViewAllTeacherWidget.h src/views/studentviews/teacherlistviewer.h src/views/studentviews/timeslotcalendar.h src/views/studentviews/meetingbooking.h src/views/studentviews/meetingcalendarviewer.h src/views/studentviews/MeetingDialog.h src/views/UserView.h src/views/TeacherView.h src/views/StudentView.h src/controllers/UserController.h src/controllers/TeacherController.h src/controllers/StudentController.h src/controllers/TeacherResponseController.h src/controllers/StudentResponseController.h src/models/User.h src/models/Meeting.h src/models/Timeslot.h src/models/Response.h src/models/Attendance.h src/repository/UserRepository.h src/repository/MeetingRepository.h src/repository/TimeslotRepository.h src/repository/AttendanceRepository.h src/utils/Utils.h src/utils/MessageUtils.h src/Status.h data/Database.h environment.h $(DISTDIR)/
	$(COPY_FILE) --parents src/client/Client1.cpp src/views/userviews/loginwidget.cpp src/views/userviews/registerwidget.cpp src/views/userviews/mainmenu.cpp src/views/teacherviews/TeacherMenuWidget.cpp src/views/teacherviews/timeslotdialog.cpp src/views/teacherviews/viewtimeslotsdialog.cpp src/views/teacherviews/update_timeslot_dialog.cpp src/views/teacherviews/teacherviewmeetingsdialog.cpp src/views/teacherviews/meetingdetaildialog.cpp src/views/teacherviews/meetinghistorydialog.cpp src/views/teacherviews/viewmeetinghistorydialog.cpp src/views/teacherviews/viewweeklymeetingsdialog.cpp src/views/teacherviews/meetingcalendarwidget.cpp src/views/studentviews/StudentMenu.cpp src/views/studentviews/ViewAllTeacherWidget.cpp src/views/studentviews/teacherlistviewer.cpp src/views/studentviews/timeslotcalendar.cpp src/views/studentviews/meetingbooking.cpp src/views/studentviews/meetingcalendarviewer.cpp src/views/studentviews/MeetingDialog.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/views/userviews/loginwidget.ui src/views/userviews/registerwidget.ui src/views/userviews/mainmenu.ui src/views/teacherviews/TeacherMenuWidget.ui src/views/teacherviews/timeslotdialog.ui src/views/teacherviews/viewtimeslotsdialog.ui src/views/teacherviews/update_timeslot_dialog.ui src/views/teacherviews/teacherviewmeetingsdialog.ui src/views/teacherviews/meetingdetaildialog.ui src/views/teacherviews/meetinghistorydialog.ui src/views/teacherviews/viewmeetinghistorydialog.ui src/views/teacherviews/viewweeklymeetingsdialog.ui src/views/studentviews/StudentMenu.ui src/views/studentviews/ViewAllTeacherWidget.ui src/views/studentviews/teacherlistviewer.ui src/views/studentviews/timeslotcalendar.ui src/views/studentviews/meetingbooking.ui src/views/studentviews/meetingcalendarviewer.ui src/views/studentviews/MeetingDialog.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: build/moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) build/moc/moc_predefs.h
build/moc/moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -Wextra -dM -E -o build/moc/moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: build/moc/moc_loginwidget.cpp build/moc/moc_registerwidget.cpp build/moc/moc_mainmenu.cpp build/moc/moc_TeacherMenuWidget.cpp build/moc/moc_timeslotdialog.cpp build/moc/moc_viewtimeslotsdialog.cpp build/moc/moc_update_timeslot_dialog.cpp build/moc/moc_teacherviewmeetingsdialog.cpp build/moc/moc_meetingdetaildialog.cpp build/moc/moc_meetinghistorydialog.cpp build/moc/moc_viewmeetinghistorydialog.cpp build/moc/moc_viewweeklymeetingsdialog.cpp build/moc/moc_meetingcalendarwidget.cpp build/moc/moc_StudentMenu.cpp build/moc/moc_ViewAllTeacherWidget.cpp build/moc/moc_teacherlistviewer.cpp build/moc/moc_timeslotcalendar.cpp build/moc/moc_meetingbooking.cpp build/moc/moc_meetingcalendarviewer.cpp build/moc/moc_MeetingDialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc/moc_loginwidget.cpp build/moc/moc_registerwidget.cpp build/moc/moc_mainmenu.cpp build/moc/moc_TeacherMenuWidget.cpp build/moc/moc_timeslotdialog.cpp build/moc/moc_viewtimeslotsdialog.cpp build/moc/moc_update_timeslot_dialog.cpp build/moc/moc_teacherviewmeetingsdialog.cpp build/moc/moc_meetingdetaildialog.cpp build/moc/moc_meetinghistorydialog.cpp build/moc/moc_viewmeetinghistorydialog.cpp build/moc/moc_viewweeklymeetingsdialog.cpp build/moc/moc_meetingcalendarwidget.cpp build/moc/moc_StudentMenu.cpp build/moc/moc_ViewAllTeacherWidget.cpp build/moc/moc_teacherlistviewer.cpp build/moc/moc_timeslotcalendar.cpp build/moc/moc_meetingbooking.cpp build/moc/moc_meetingcalendarviewer.cpp build/moc/moc_MeetingDialog.cpp
build/moc/moc_loginwidget.cpp: src/views/userviews/loginwidget.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/controllers' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/models' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/repository' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/utils' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/userviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/teacherviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/studentviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/data' -I/usr/include/cppconn -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/views/userviews/loginwidget.h -o build/moc/moc_loginwidget.cpp

build/moc/moc_registerwidget.cpp: src/views/userviews/registerwidget.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/controllers' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/models' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/repository' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/utils' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/userviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/teacherviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/studentviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/data' -I/usr/include/cppconn -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/views/userviews/registerwidget.h -o build/moc/moc_registerwidget.cpp

build/moc/moc_mainmenu.cpp: src/views/userviews/mainmenu.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/controllers' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/models' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/repository' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/utils' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/userviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/teacherviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/studentviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/data' -I/usr/include/cppconn -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/views/userviews/mainmenu.h -o build/moc/moc_mainmenu.cpp

build/moc/moc_TeacherMenuWidget.cpp: src/views/teacherviews/TeacherMenuWidget.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/controllers' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/models' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/repository' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/utils' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/userviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/teacherviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/studentviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/data' -I/usr/include/cppconn -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/views/teacherviews/TeacherMenuWidget.h -o build/moc/moc_TeacherMenuWidget.cpp

build/moc/moc_timeslotdialog.cpp: src/views/teacherviews/timeslotdialog.h \
		src/models/Timeslot.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/controllers' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/models' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/repository' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/utils' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/userviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/teacherviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/studentviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/data' -I/usr/include/cppconn -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/views/teacherviews/timeslotdialog.h -o build/moc/moc_timeslotdialog.cpp

build/moc/moc_viewtimeslotsdialog.cpp: src/views/teacherviews/viewtimeslotsdialog.h \
		src/models/Timeslot.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/controllers' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/models' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/repository' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/utils' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/userviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/teacherviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/studentviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/data' -I/usr/include/cppconn -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/views/teacherviews/viewtimeslotsdialog.h -o build/moc/moc_viewtimeslotsdialog.cpp

build/moc/moc_update_timeslot_dialog.cpp: src/views/teacherviews/update_timeslot_dialog.h \
		src/models/Timeslot.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/controllers' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/models' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/repository' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/utils' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/userviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/teacherviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/studentviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/data' -I/usr/include/cppconn -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/views/teacherviews/update_timeslot_dialog.h -o build/moc/moc_update_timeslot_dialog.cpp

build/moc/moc_teacherviewmeetingsdialog.cpp: src/views/teacherviews/teacherviewmeetingsdialog.h \
		src/models/Meeting.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/controllers' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/models' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/repository' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/utils' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/userviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/teacherviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/studentviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/data' -I/usr/include/cppconn -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/views/teacherviews/teacherviewmeetingsdialog.h -o build/moc/moc_teacherviewmeetingsdialog.cpp

build/moc/moc_meetingdetaildialog.cpp: src/views/teacherviews/meetingdetaildialog.h \
		src/models/Meeting.h \
		src/models/User.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/controllers' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/models' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/repository' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/utils' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/userviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/teacherviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/studentviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/data' -I/usr/include/cppconn -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/views/teacherviews/meetingdetaildialog.h -o build/moc/moc_meetingdetaildialog.cpp

build/moc/moc_meetinghistorydialog.cpp: src/views/teacherviews/meetinghistorydialog.h \
		src/models/Meeting.h \
		src/models/User.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/controllers' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/models' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/repository' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/utils' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/userviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/teacherviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/studentviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/data' -I/usr/include/cppconn -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/views/teacherviews/meetinghistorydialog.h -o build/moc/moc_meetinghistorydialog.cpp

build/moc/moc_viewmeetinghistorydialog.cpp: src/views/teacherviews/viewmeetinghistorydialog.h \
		src/models/Meeting.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/controllers' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/models' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/repository' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/utils' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/userviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/teacherviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/studentviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/data' -I/usr/include/cppconn -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/views/teacherviews/viewmeetinghistorydialog.h -o build/moc/moc_viewmeetinghistorydialog.cpp

build/moc/moc_viewweeklymeetingsdialog.cpp: src/views/teacherviews/viewweeklymeetingsdialog.h \
		src/models/Meeting.h \
		src/models/User.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/controllers' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/models' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/repository' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/utils' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/userviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/teacherviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/studentviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/data' -I/usr/include/cppconn -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/views/teacherviews/viewweeklymeetingsdialog.h -o build/moc/moc_viewweeklymeetingsdialog.cpp

build/moc/moc_meetingcalendarwidget.cpp: src/views/teacherviews/meetingcalendarwidget.h \
		src/models/Meeting.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/controllers' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/models' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/repository' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/utils' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/userviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/teacherviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/studentviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/data' -I/usr/include/cppconn -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/views/teacherviews/meetingcalendarwidget.h -o build/moc/moc_meetingcalendarwidget.cpp

build/moc/moc_StudentMenu.cpp: src/views/studentviews/StudentMenu.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/controllers' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/models' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/repository' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/utils' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/userviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/teacherviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/studentviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/data' -I/usr/include/cppconn -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/views/studentviews/StudentMenu.h -o build/moc/moc_StudentMenu.cpp

build/moc/moc_ViewAllTeacherWidget.cpp: src/views/studentviews/ViewAllTeacherWidget.h \
		build/ui/ui_ViewAllTeacherWidget.h \
		src/models/User.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/controllers' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/models' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/repository' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/utils' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/userviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/teacherviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/studentviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/data' -I/usr/include/cppconn -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/views/studentviews/ViewAllTeacherWidget.h -o build/moc/moc_ViewAllTeacherWidget.cpp

build/moc/moc_teacherlistviewer.cpp: src/views/studentviews/teacherlistviewer.h \
		src/models/User.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/controllers' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/models' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/repository' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/utils' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/userviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/teacherviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/studentviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/data' -I/usr/include/cppconn -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/views/studentviews/teacherlistviewer.h -o build/moc/moc_teacherlistviewer.cpp

build/moc/moc_timeslotcalendar.cpp: src/views/studentviews/timeslotcalendar.h \
		src/models/Timeslot.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/controllers' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/models' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/repository' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/utils' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/userviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/teacherviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/studentviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/data' -I/usr/include/cppconn -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/views/studentviews/timeslotcalendar.h -o build/moc/moc_timeslotcalendar.cpp

build/moc/moc_meetingbooking.cpp: src/views/studentviews/meetingbooking.h \
		src/models/Meeting.h \
		src/models/Timeslot.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/controllers' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/models' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/repository' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/utils' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/userviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/teacherviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/studentviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/data' -I/usr/include/cppconn -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/views/studentviews/meetingbooking.h -o build/moc/moc_meetingbooking.cpp

build/moc/moc_meetingcalendarviewer.cpp: src/views/studentviews/meetingcalendarviewer.h \
		src/models/Meeting.h \
		src/models/User.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/controllers' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/models' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/repository' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/utils' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/userviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/teacherviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/studentviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/data' -I/usr/include/cppconn -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/views/studentviews/meetingcalendarviewer.h -o build/moc/moc_meetingcalendarviewer.cpp

build/moc/moc_MeetingDialog.cpp: src/views/studentviews/MeetingDialog.h \
		src/models/Meeting.h \
		src/models/User.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/build/moc/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/controllers' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/models' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/repository' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/utils' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/userviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/teacherviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/src/views/studentviews' -I'/mnt/d/2025.1/Lap trinh mang/Meeting_Scheduler_App/data' -I/usr/include/cppconn -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/views/studentviews/MeetingDialog.h -o build/moc/moc_MeetingDialog.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: build/ui/ui_loginwidget.h build/ui/ui_registerwidget.h build/ui/ui_mainmenu.h build/ui/ui_TeacherMenuWidget.h build/ui/ui_timeslotdialog.h build/ui/ui_viewtimeslotsdialog.h build/ui/ui_update_timeslot_dialog.h build/ui/ui_teacherviewmeetingsdialog.h build/ui/ui_meetingdetaildialog.h build/ui/ui_meetinghistorydialog.h build/ui/ui_viewmeetinghistorydialog.h build/ui/ui_viewweeklymeetingsdialog.h build/ui/ui_StudentMenu.h build/ui/ui_ViewAllTeacherWidget.h build/ui/ui_teacherlistviewer.h build/ui/ui_timeslotcalendar.h build/ui/ui_meetingbooking.h build/ui/ui_meetingcalendarviewer.h build/ui/ui_MeetingDialog.h
compiler_uic_clean:
	-$(DEL_FILE) build/ui/ui_loginwidget.h build/ui/ui_registerwidget.h build/ui/ui_mainmenu.h build/ui/ui_TeacherMenuWidget.h build/ui/ui_timeslotdialog.h build/ui/ui_viewtimeslotsdialog.h build/ui/ui_update_timeslot_dialog.h build/ui/ui_teacherviewmeetingsdialog.h build/ui/ui_meetingdetaildialog.h build/ui/ui_meetinghistorydialog.h build/ui/ui_viewmeetinghistorydialog.h build/ui/ui_viewweeklymeetingsdialog.h build/ui/ui_StudentMenu.h build/ui/ui_ViewAllTeacherWidget.h build/ui/ui_teacherlistviewer.h build/ui/ui_timeslotcalendar.h build/ui/ui_meetingbooking.h build/ui/ui_meetingcalendarviewer.h build/ui/ui_MeetingDialog.h
build/ui/ui_loginwidget.h: src/views/userviews/loginwidget.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/views/userviews/loginwidget.ui -o build/ui/ui_loginwidget.h

build/ui/ui_registerwidget.h: src/views/userviews/registerwidget.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/views/userviews/registerwidget.ui -o build/ui/ui_registerwidget.h

build/ui/ui_mainmenu.h: src/views/userviews/mainmenu.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/views/userviews/mainmenu.ui -o build/ui/ui_mainmenu.h

build/ui/ui_TeacherMenuWidget.h: src/views/teacherviews/TeacherMenuWidget.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/views/teacherviews/TeacherMenuWidget.ui -o build/ui/ui_TeacherMenuWidget.h

build/ui/ui_timeslotdialog.h: src/views/teacherviews/timeslotdialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/views/teacherviews/timeslotdialog.ui -o build/ui/ui_timeslotdialog.h

build/ui/ui_viewtimeslotsdialog.h: src/views/teacherviews/viewtimeslotsdialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/views/teacherviews/viewtimeslotsdialog.ui -o build/ui/ui_viewtimeslotsdialog.h

build/ui/ui_update_timeslot_dialog.h: src/views/teacherviews/update_timeslot_dialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/views/teacherviews/update_timeslot_dialog.ui -o build/ui/ui_update_timeslot_dialog.h

build/ui/ui_teacherviewmeetingsdialog.h: src/views/teacherviews/teacherviewmeetingsdialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/views/teacherviews/teacherviewmeetingsdialog.ui -o build/ui/ui_teacherviewmeetingsdialog.h

build/ui/ui_meetingdetaildialog.h: src/views/teacherviews/meetingdetaildialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/views/teacherviews/meetingdetaildialog.ui -o build/ui/ui_meetingdetaildialog.h

build/ui/ui_meetinghistorydialog.h: src/views/teacherviews/meetinghistorydialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/views/teacherviews/meetinghistorydialog.ui -o build/ui/ui_meetinghistorydialog.h

build/ui/ui_viewmeetinghistorydialog.h: src/views/teacherviews/viewmeetinghistorydialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/views/teacherviews/viewmeetinghistorydialog.ui -o build/ui/ui_viewmeetinghistorydialog.h

build/ui/ui_viewweeklymeetingsdialog.h: src/views/teacherviews/viewweeklymeetingsdialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/views/teacherviews/viewweeklymeetingsdialog.ui -o build/ui/ui_viewweeklymeetingsdialog.h

build/ui/ui_StudentMenu.h: src/views/studentviews/StudentMenu.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/views/studentviews/StudentMenu.ui -o build/ui/ui_StudentMenu.h

build/ui/ui_ViewAllTeacherWidget.h: src/views/studentviews/ViewAllTeacherWidget.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/views/studentviews/ViewAllTeacherWidget.ui -o build/ui/ui_ViewAllTeacherWidget.h

build/ui/ui_teacherlistviewer.h: src/views/studentviews/teacherlistviewer.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/views/studentviews/teacherlistviewer.ui -o build/ui/ui_teacherlistviewer.h

build/ui/ui_timeslotcalendar.h: src/views/studentviews/timeslotcalendar.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/views/studentviews/timeslotcalendar.ui -o build/ui/ui_timeslotcalendar.h

build/ui/ui_meetingbooking.h: src/views/studentviews/meetingbooking.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/views/studentviews/meetingbooking.ui -o build/ui/ui_meetingbooking.h

build/ui/ui_meetingcalendarviewer.h: src/views/studentviews/meetingcalendarviewer.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/views/studentviews/meetingcalendarviewer.ui -o build/ui/ui_meetingcalendarviewer.h

build/ui/ui_MeetingDialog.h: src/views/studentviews/MeetingDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/views/studentviews/MeetingDialog.ui -o build/ui/ui_MeetingDialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

build/obj/Client1.o: src/client/Client1.cpp src/controllers/ClientController.h \
		src/models/Response.h \
		src/models/User.h \
		src/repository/TimeslotRepository.h \
		data/Database.h \
		environment.h \
		src/models/Timeslot.h \
		src/utils/Utils.h \
		src/repository/UserRepository.h \
		src/controllers/StudentController.h \
		src/models/Meeting.h \
		src/controllers/TeacherController.h \
		src/controllers/ResponseController.h \
		src/controllers/UserController.h \
		src/utils/MessageUtils.h \
		src/Status.h \
		src/views/StudentView.h \
		src/views/TeacherView.h \
		src/views/UserView.h \
		src/views/teacherviews/timeslotdialog.h \
		src/views/teacherviews/viewtimeslotsdialog.h \
		src/views/teacherviews/update_timeslot_dialog.h \
		src/views/teacherviews/teacherviewmeetingsdialog.h \
		src/views/teacherviews/meetingdetaildialog.h \
		src/views/teacherviews/meetinghistorydialog.h \
		src/views/teacherviews/TeacherMenuWidget.h \
		src/views/teacherviews/viewmeetinghistorydialog.h \
		src/views/teacherviews/viewweeklymeetingsdialog.h \
		src/views/userviews/loginwidget.h \
		src/views/userviews/mainmenu.h \
		src/views/userviews/registerwidget.h \
		src/views/studentviews/ViewAllTeacherWidget.h \
		build/ui/ui_ViewAllTeacherWidget.h \
		src/views/studentviews/teacherlistviewer.h \
		src/views/studentviews/timeslotcalendar.h \
		src/views/studentviews/meetingbooking.h \
		src/views/studentviews/meetingcalendarviewer.h \
		src/views/studentviews/MeetingDialog.h \
		src/views/studentviews/StudentMenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/Client1.o src/client/Client1.cpp

build/obj/loginwidget.o: src/views/userviews/loginwidget.cpp src/views/userviews/loginwidget.h \
		build/ui/ui_loginwidget.h \
		src/utils/PopupUtils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/loginwidget.o src/views/userviews/loginwidget.cpp

build/obj/registerwidget.o: src/views/userviews/registerwidget.cpp src/views/userviews/registerwidget.h \
		build/ui/ui_registerwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/registerwidget.o src/views/userviews/registerwidget.cpp

build/obj/mainmenu.o: src/views/userviews/mainmenu.cpp src/views/userviews/mainmenu.h \
		build/ui/ui_mainmenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/mainmenu.o src/views/userviews/mainmenu.cpp

build/obj/TeacherMenuWidget.o: src/views/teacherviews/TeacherMenuWidget.cpp src/views/teacherviews/TeacherMenuWidget.h \
		build/ui/ui_TeacherMenuWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/TeacherMenuWidget.o src/views/teacherviews/TeacherMenuWidget.cpp

build/obj/timeslotdialog.o: src/views/teacherviews/timeslotdialog.cpp src/views/teacherviews/timeslotdialog.h \
		src/models/Timeslot.h \
		build/ui/ui_timeslotdialog.h \
		src/utils/PopupUtils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/timeslotdialog.o src/views/teacherviews/timeslotdialog.cpp

build/obj/viewtimeslotsdialog.o: src/views/teacherviews/viewtimeslotsdialog.cpp src/views/teacherviews/viewtimeslotsdialog.h \
		src/models/Timeslot.h \
		build/ui/ui_viewtimeslotsdialog.h \
		src/utils/PopupUtils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/viewtimeslotsdialog.o src/views/teacherviews/viewtimeslotsdialog.cpp

build/obj/update_timeslot_dialog.o: src/views/teacherviews/update_timeslot_dialog.cpp src/views/teacherviews/update_timeslot_dialog.h \
		src/models/Timeslot.h \
		build/ui/ui_update_timeslot_dialog.h \
		src/utils/PopupUtils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/update_timeslot_dialog.o src/views/teacherviews/update_timeslot_dialog.cpp

build/obj/teacherviewmeetingsdialog.o: src/views/teacherviews/teacherviewmeetingsdialog.cpp src/views/teacherviews/teacherviewmeetingsdialog.h \
		src/models/Meeting.h \
		build/ui/ui_teacherviewmeetingsdialog.h \
		src/utils/PopupUtils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/teacherviewmeetingsdialog.o src/views/teacherviews/teacherviewmeetingsdialog.cpp

build/obj/meetingdetaildialog.o: src/views/teacherviews/meetingdetaildialog.cpp src/views/teacherviews/meetingdetaildialog.h \
		src/models/Meeting.h \
		src/models/User.h \
		build/ui/ui_meetingdetaildialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/meetingdetaildialog.o src/views/teacherviews/meetingdetaildialog.cpp

build/obj/meetinghistorydialog.o: src/views/teacherviews/meetinghistorydialog.cpp src/views/teacherviews/meetinghistorydialog.h \
		src/models/Meeting.h \
		src/models/User.h \
		build/ui/ui_meetinghistorydialog.h \
		src/utils/PopupUtils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/meetinghistorydialog.o src/views/teacherviews/meetinghistorydialog.cpp

build/obj/viewmeetinghistorydialog.o: src/views/teacherviews/viewmeetinghistorydialog.cpp src/views/teacherviews/viewmeetinghistorydialog.h \
		src/models/Meeting.h \
		build/ui/ui_viewmeetinghistorydialog.h \
		src/utils/PopupUtils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/viewmeetinghistorydialog.o src/views/teacherviews/viewmeetinghistorydialog.cpp

build/obj/viewweeklymeetingsdialog.o: src/views/teacherviews/viewweeklymeetingsdialog.cpp src/views/teacherviews/viewweeklymeetingsdialog.h \
		src/models/Meeting.h \
		src/models/User.h \
		build/ui/ui_viewweeklymeetingsdialog.h \
		src/utils/PopupUtils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/viewweeklymeetingsdialog.o src/views/teacherviews/viewweeklymeetingsdialog.cpp

build/obj/meetingcalendarwidget.o: src/views/teacherviews/meetingcalendarwidget.cpp src/views/teacherviews/meetingcalendarwidget.h \
		src/models/Meeting.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/meetingcalendarwidget.o src/views/teacherviews/meetingcalendarwidget.cpp

build/obj/StudentMenu.o: src/views/studentviews/StudentMenu.cpp src/views/studentviews/StudentMenu.h \
		build/ui/ui_StudentMenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/StudentMenu.o src/views/studentviews/StudentMenu.cpp

build/obj/ViewAllTeacherWidget.o: src/views/studentviews/ViewAllTeacherWidget.cpp src/views/studentviews/ViewAllTeacherWidget.h \
		build/ui/ui_ViewAllTeacherWidget.h \
		src/models/User.h \
		src/utils/PopupUtils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/ViewAllTeacherWidget.o src/views/studentviews/ViewAllTeacherWidget.cpp

build/obj/teacherlistviewer.o: src/views/studentviews/teacherlistviewer.cpp src/views/studentviews/teacherlistviewer.h \
		src/models/User.h \
		build/ui/ui_teacherlistviewer.h \
		src/utils/PopupUtils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/teacherlistviewer.o src/views/studentviews/teacherlistviewer.cpp

build/obj/timeslotcalendar.o: src/views/studentviews/timeslotcalendar.cpp src/views/studentviews/timeslotcalendar.h \
		src/models/Timeslot.h \
		build/ui/ui_timeslotcalendar.h \
		src/utils/PopupUtils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/timeslotcalendar.o src/views/studentviews/timeslotcalendar.cpp

build/obj/meetingbooking.o: src/views/studentviews/meetingbooking.cpp src/views/studentviews/meetingbooking.h \
		src/models/Meeting.h \
		src/models/Timeslot.h \
		build/ui/ui_meetingbooking.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/meetingbooking.o src/views/studentviews/meetingbooking.cpp

build/obj/meetingcalendarviewer.o: src/views/studentviews/meetingcalendarviewer.cpp src/views/studentviews/meetingcalendarviewer.h \
		src/models/Meeting.h \
		src/models/User.h \
		build/ui/ui_meetingcalendarviewer.h \
		src/utils/PopupUtils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/meetingcalendarviewer.o src/views/studentviews/meetingcalendarviewer.cpp

build/obj/MeetingDialog.o: src/views/studentviews/MeetingDialog.cpp src/views/studentviews/MeetingDialog.h \
		src/models/Meeting.h \
		src/models/User.h \
		build/ui/ui_MeetingDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/MeetingDialog.o src/views/studentviews/MeetingDialog.cpp

build/obj/moc_loginwidget.o: build/moc/moc_loginwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_loginwidget.o build/moc/moc_loginwidget.cpp

build/obj/moc_registerwidget.o: build/moc/moc_registerwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_registerwidget.o build/moc/moc_registerwidget.cpp

build/obj/moc_mainmenu.o: build/moc/moc_mainmenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_mainmenu.o build/moc/moc_mainmenu.cpp

build/obj/moc_TeacherMenuWidget.o: build/moc/moc_TeacherMenuWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_TeacherMenuWidget.o build/moc/moc_TeacherMenuWidget.cpp

build/obj/moc_timeslotdialog.o: build/moc/moc_timeslotdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_timeslotdialog.o build/moc/moc_timeslotdialog.cpp

build/obj/moc_viewtimeslotsdialog.o: build/moc/moc_viewtimeslotsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_viewtimeslotsdialog.o build/moc/moc_viewtimeslotsdialog.cpp

build/obj/moc_update_timeslot_dialog.o: build/moc/moc_update_timeslot_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_update_timeslot_dialog.o build/moc/moc_update_timeslot_dialog.cpp

build/obj/moc_teacherviewmeetingsdialog.o: build/moc/moc_teacherviewmeetingsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_teacherviewmeetingsdialog.o build/moc/moc_teacherviewmeetingsdialog.cpp

build/obj/moc_meetingdetaildialog.o: build/moc/moc_meetingdetaildialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_meetingdetaildialog.o build/moc/moc_meetingdetaildialog.cpp

build/obj/moc_meetinghistorydialog.o: build/moc/moc_meetinghistorydialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_meetinghistorydialog.o build/moc/moc_meetinghistorydialog.cpp

build/obj/moc_viewmeetinghistorydialog.o: build/moc/moc_viewmeetinghistorydialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_viewmeetinghistorydialog.o build/moc/moc_viewmeetinghistorydialog.cpp

build/obj/moc_viewweeklymeetingsdialog.o: build/moc/moc_viewweeklymeetingsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_viewweeklymeetingsdialog.o build/moc/moc_viewweeklymeetingsdialog.cpp

build/obj/moc_meetingcalendarwidget.o: build/moc/moc_meetingcalendarwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_meetingcalendarwidget.o build/moc/moc_meetingcalendarwidget.cpp

build/obj/moc_StudentMenu.o: build/moc/moc_StudentMenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_StudentMenu.o build/moc/moc_StudentMenu.cpp

build/obj/moc_ViewAllTeacherWidget.o: build/moc/moc_ViewAllTeacherWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_ViewAllTeacherWidget.o build/moc/moc_ViewAllTeacherWidget.cpp

build/obj/moc_teacherlistviewer.o: build/moc/moc_teacherlistviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_teacherlistviewer.o build/moc/moc_teacherlistviewer.cpp

build/obj/moc_timeslotcalendar.o: build/moc/moc_timeslotcalendar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_timeslotcalendar.o build/moc/moc_timeslotcalendar.cpp

build/obj/moc_meetingbooking.o: build/moc/moc_meetingbooking.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_meetingbooking.o build/moc/moc_meetingbooking.cpp

build/obj/moc_meetingcalendarviewer.o: build/moc/moc_meetingcalendarviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_meetingcalendarviewer.o build/moc/moc_meetingcalendarviewer.cpp

build/obj/moc_MeetingDialog.o: build/moc/moc_MeetingDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_MeetingDialog.o build/moc/moc_MeetingDialog.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/MeetingScheduler/bin || mkdir -p $(INSTALL_ROOT)/opt/MeetingScheduler/bin
	$(QINSTALL_PROGRAM) build/$(QMAKE_TARGET) $(INSTALL_ROOT)/opt/MeetingScheduler/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/MeetingScheduler/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/MeetingScheduler/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/MeetingScheduler/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

